// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_eucl_dist_vec_mat_rcpp
NumericVector compute_eucl_dist_vec_mat_rcpp(const NumericVector& vec, const NumericMatrix& mtx);
RcppExport SEXP _BEAMM_KCCAACCA_compute_eucl_dist_vec_mat_rcpp(SEXP vecSEXP, SEXP mtxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mtx(mtxSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_eucl_dist_vec_mat_rcpp(vec, mtx));
    return rcpp_result_gen;
END_RCPP
}
// compute_hmin_kcca_rcpp
arma::mat compute_hmin_kcca_rcpp(const arma::mat& uX, const arma::mat& uY, const double& h);
RcppExport SEXP _BEAMM_KCCAACCA_compute_hmin_kcca_rcpp(SEXP uXSEXP, SEXP uYSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type uX(uXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type uY(uYSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hmin_kcca_rcpp(uX, uY, h));
    return rcpp_result_gen;
END_RCPP
}
// compute_hmin_kcca_d1_rcpp
arma::mat compute_hmin_kcca_d1_rcpp(const arma::vec& uX, const arma::vec& uY, const double& h);
RcppExport SEXP _BEAMM_KCCAACCA_compute_hmin_kcca_d1_rcpp(SEXP uXSEXP, SEXP uYSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type uX(uXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type uY(uYSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hmin_kcca_d1_rcpp(uX, uY, h));
    return rcpp_result_gen;
END_RCPP
}
// compute_hmin_with_comp_mtx_kcca_rcpp
arma::mat compute_hmin_with_comp_mtx_kcca_rcpp(const arma::mat& uX, const arma::mat& uY, const arma::mat& comp_mtx, const double& h);
RcppExport SEXP _BEAMM_KCCAACCA_compute_hmin_with_comp_mtx_kcca_rcpp(SEXP uXSEXP, SEXP uYSEXP, SEXP comp_mtxSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type uX(uXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type uY(uYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type comp_mtx(comp_mtxSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hmin_with_comp_mtx_kcca_rcpp(uX, uY, comp_mtx, h));
    return rcpp_result_gen;
END_RCPP
}
// compute_hmin_with_comp_mtx_kcca_d1_rcpp
arma::mat compute_hmin_with_comp_mtx_kcca_d1_rcpp(const arma::vec& uX, const arma::vec& uY, const arma::mat& comp_mtx, const double& h);
RcppExport SEXP _BEAMM_KCCAACCA_compute_hmin_with_comp_mtx_kcca_d1_rcpp(SEXP uXSEXP, SEXP uYSEXP, SEXP comp_mtxSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type uX(uXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type uY(uYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type comp_mtx(comp_mtxSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hmin_with_comp_mtx_kcca_d1_rcpp(uX, uY, comp_mtx, h));
    return rcpp_result_gen;
END_RCPP
}
// compute_mtx_compatibilities_rcpp
List compute_mtx_compatibilities_rcpp(const IntegerMatrix& mtx_n_diff_CV);
RcppExport SEXP _BEAMM_KCCAACCA_compute_mtx_compatibilities_rcpp(SEXP mtx_n_diff_CVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type mtx_n_diff_CV(mtx_n_diff_CVSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_mtx_compatibilities_rcpp(mtx_n_diff_CV));
    return rcpp_result_gen;
END_RCPP
}
// compute_mtx_compatibilities_reg_rcpp
List compute_mtx_compatibilities_reg_rcpp(const IntegerMatrix& mtx_n_diff_CV);
RcppExport SEXP _BEAMM_KCCAACCA_compute_mtx_compatibilities_reg_rcpp(SEXP mtx_n_diff_CVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type mtx_n_diff_CV(mtx_n_diff_CVSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_mtx_compatibilities_reg_rcpp(mtx_n_diff_CV));
    return rcpp_result_gen;
END_RCPP
}
// compute_mtx_n_diff_CV_rcpp
NumericMatrix compute_mtx_n_diff_CV_rcpp(const NumericMatrix& mtx_don, const NumericMatrix& mtx_rec);
RcppExport SEXP _BEAMM_KCCAACCA_compute_mtx_n_diff_CV_rcpp(SEXP mtx_donSEXP, SEXP mtx_recSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mtx_don(mtx_donSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mtx_rec(mtx_recSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_mtx_n_diff_CV_rcpp(mtx_don, mtx_rec));
    return rcpp_result_gen;
END_RCPP
}
// compute_omega_kcca_rcpp
arma::mat compute_omega_kcca_rcpp(const arma::mat& uX, const arma::mat& uY, const arma::vec& hmin);
RcppExport SEXP _BEAMM_KCCAACCA_compute_omega_kcca_rcpp(SEXP uXSEXP, SEXP uYSEXP, SEXP hminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type uX(uXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type uY(uYSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type hmin(hminSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_omega_kcca_rcpp(uX, uY, hmin));
    return rcpp_result_gen;
END_RCPP
}
// compute_omega_kcca_d1_rcpp
arma::mat compute_omega_kcca_d1_rcpp(const arma::vec& uX, const arma::vec& uY, const arma::vec& hmin);
RcppExport SEXP _BEAMM_KCCAACCA_compute_omega_kcca_d1_rcpp(SEXP uXSEXP, SEXP uYSEXP, SEXP hminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type uX(uXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type uY(uYSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type hmin(hminSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_omega_kcca_d1_rcpp(uX, uY, hmin));
    return rcpp_result_gen;
END_RCPP
}
// wtd_col_means_rcpp
NumericVector wtd_col_means_rcpp(const NumericMatrix& mtx, const NumericVector& wt);
RcppExport SEXP _BEAMM_KCCAACCA_wtd_col_means_rcpp(SEXP mtxSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mtx(mtxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(wtd_col_means_rcpp(mtx, wt));
    return rcpp_result_gen;
END_RCPP
}
// wtd_col_sd_rcpp
NumericVector wtd_col_sd_rcpp(const NumericMatrix& mtx, const NumericVector& wt);
RcppExport SEXP _BEAMM_KCCAACCA_wtd_col_sd_rcpp(SEXP mtxSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mtx(mtxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(wtd_col_sd_rcpp(mtx, wt));
    return rcpp_result_gen;
END_RCPP
}
// wtd_col_var_rcpp
NumericVector wtd_col_var_rcpp(const NumericMatrix& mtx, const NumericVector& wt);
RcppExport SEXP _BEAMM_KCCAACCA_wtd_col_var_rcpp(SEXP mtxSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mtx(mtxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(wtd_col_var_rcpp(mtx, wt));
    return rcpp_result_gen;
END_RCPP
}
// wtd_mean_rcpp
double wtd_mean_rcpp(const NumericVector& vec, const NumericVector& wt);
RcppExport SEXP _BEAMM_KCCAACCA_wtd_mean_rcpp(SEXP vecSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(wtd_mean_rcpp(vec, wt));
    return rcpp_result_gen;
END_RCPP
}
// wtd_sd_rcpp
double wtd_sd_rcpp(const NumericVector& vec, const NumericVector& wt);
RcppExport SEXP _BEAMM_KCCAACCA_wtd_sd_rcpp(SEXP vecSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(wtd_sd_rcpp(vec, wt));
    return rcpp_result_gen;
END_RCPP
}
// wtd_var_rcpp
double wtd_var_rcpp(const NumericVector& vec, const NumericVector& wt);
RcppExport SEXP _BEAMM_KCCAACCA_wtd_var_rcpp(SEXP vecSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(wtd_var_rcpp(vec, wt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BEAMM_KCCAACCA_compute_eucl_dist_vec_mat_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_eucl_dist_vec_mat_rcpp, 2},
    {"_BEAMM_KCCAACCA_compute_hmin_kcca_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_hmin_kcca_rcpp, 3},
    {"_BEAMM_KCCAACCA_compute_hmin_kcca_d1_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_hmin_kcca_d1_rcpp, 3},
    {"_BEAMM_KCCAACCA_compute_hmin_with_comp_mtx_kcca_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_hmin_with_comp_mtx_kcca_rcpp, 4},
    {"_BEAMM_KCCAACCA_compute_hmin_with_comp_mtx_kcca_d1_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_hmin_with_comp_mtx_kcca_d1_rcpp, 4},
    {"_BEAMM_KCCAACCA_compute_mtx_compatibilities_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_mtx_compatibilities_rcpp, 1},
    {"_BEAMM_KCCAACCA_compute_mtx_compatibilities_reg_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_mtx_compatibilities_reg_rcpp, 1},
    {"_BEAMM_KCCAACCA_compute_mtx_n_diff_CV_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_mtx_n_diff_CV_rcpp, 2},
    {"_BEAMM_KCCAACCA_compute_omega_kcca_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_omega_kcca_rcpp, 3},
    {"_BEAMM_KCCAACCA_compute_omega_kcca_d1_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_compute_omega_kcca_d1_rcpp, 3},
    {"_BEAMM_KCCAACCA_wtd_col_means_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_wtd_col_means_rcpp, 2},
    {"_BEAMM_KCCAACCA_wtd_col_sd_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_wtd_col_sd_rcpp, 2},
    {"_BEAMM_KCCAACCA_wtd_col_var_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_wtd_col_var_rcpp, 2},
    {"_BEAMM_KCCAACCA_wtd_mean_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_wtd_mean_rcpp, 2},
    {"_BEAMM_KCCAACCA_wtd_sd_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_wtd_sd_rcpp, 2},
    {"_BEAMM_KCCAACCA_wtd_var_rcpp", (DL_FUNC) &_BEAMM_KCCAACCA_wtd_var_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BEAMM_KCCAACCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
