# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_eucl_dist_vec_mat_rcpp <- function(vec, mtx) {
    .Call(`_BEAMM_KCCAACCA_compute_eucl_dist_vec_mat_rcpp`, vec, mtx)
}

compute_hmin_kcca_rcpp <- function(uX, uY, h) {
    .Call(`_BEAMM_KCCAACCA_compute_hmin_kcca_rcpp`, uX, uY, h)
}

compute_hmin_kcca_d1_rcpp <- function(uX, uY, h) {
    .Call(`_BEAMM_KCCAACCA_compute_hmin_kcca_d1_rcpp`, uX, uY, h)
}

compute_hmin_with_comp_mtx_kcca_rcpp <- function(uX, uY, comp_mtx, h) {
    .Call(`_BEAMM_KCCAACCA_compute_hmin_with_comp_mtx_kcca_rcpp`, uX, uY, comp_mtx, h)
}

compute_hmin_with_comp_mtx_kcca_d1_rcpp <- function(uX, uY, comp_mtx, h) {
    .Call(`_BEAMM_KCCAACCA_compute_hmin_with_comp_mtx_kcca_d1_rcpp`, uX, uY, comp_mtx, h)
}

compute_mtx_compatibilities_rcpp <- function(mtx_n_diff_CV) {
    .Call(`_BEAMM_KCCAACCA_compute_mtx_compatibilities_rcpp`, mtx_n_diff_CV)
}

compute_mtx_compatibilities_reg_rcpp <- function(mtx_n_diff_CV) {
    .Call(`_BEAMM_KCCAACCA_compute_mtx_compatibilities_reg_rcpp`, mtx_n_diff_CV)
}

compute_mtx_n_diff_CV_rcpp <- function(mtx_don, mtx_rec) {
    .Call(`_BEAMM_KCCAACCA_compute_mtx_n_diff_CV_rcpp`, mtx_don, mtx_rec)
}

compute_omega_kcca_rcpp <- function(uX, uY, hmin) {
    .Call(`_BEAMM_KCCAACCA_compute_omega_kcca_rcpp`, uX, uY, hmin)
}

compute_omega_kcca_d1_rcpp <- function(uX, uY, hmin) {
    .Call(`_BEAMM_KCCAACCA_compute_omega_kcca_d1_rcpp`, uX, uY, hmin)
}

wtd_col_means_rcpp <- function(mtx, wt) {
    .Call(`_BEAMM_KCCAACCA_wtd_col_means_rcpp`, mtx, wt)
}

wtd_col_sd_rcpp <- function(mtx, wt) {
    .Call(`_BEAMM_KCCAACCA_wtd_col_sd_rcpp`, mtx, wt)
}

wtd_col_var_rcpp <- function(mtx, wt) {
    .Call(`_BEAMM_KCCAACCA_wtd_col_var_rcpp`, mtx, wt)
}

wtd_mean_rcpp <- function(vec, wt) {
    .Call(`_BEAMM_KCCAACCA_wtd_mean_rcpp`, vec, wt)
}

wtd_sd_rcpp <- function(vec, wt) {
    .Call(`_BEAMM_KCCAACCA_wtd_sd_rcpp`, vec, wt)
}

wtd_var_rcpp <- function(vec, wt) {
    .Call(`_BEAMM_KCCAACCA_wtd_var_rcpp`, vec, wt)
}

